version: "3.8"

services:
  app:
    build:
      context: .
    container_name: bagisto_app
    restart: unless-stopped
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
  

  db:
    image: mysql:8.0
    container_name: bagisto_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bagisto
      MYSQL_USER: bagisto
      MYSQL_PASSWORD: Bagisto@123
